server:
  port: 8080  # 서버 포트 설정 (기본값: 8080)

spring:
  datasource:
    url: jdbc:log4jdbc:oracle:thin:@112.220.114.130:1521:xe
    username: team1_202404F
    password: java
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        format_sql: true
    show-sql: true

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB